name = "IntervalWavelets"
uuid = "0605f816-0bd7-11ea-1bbe-fb0a4d530a66"
authors = ["Robert Dahl Jacobsen <git@dahl-jacobsen.dk>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
